
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ardakc
 */

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jRadioButton2.setSelected(true);
           jTextField3.setVisible(false);
        jLabel3.setVisible(false);
        jButton4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KCS File Shredder 1.0 Professional Edition");

        jLabel1.setText("Konum");

        jButton1.setText("Başlat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setText("1000");

        jLabel2.setText("Parçalama Sayısı");

        jRadioButton1.setText("Klasör İçerisindeki Dosyaları Parçalama Modu");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Tek Bir Dosyayı Parçalama Modu");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Parçalanmasını İstemediğin Uzantıya Sahip Dosya örnek = .mp4 .exe .jar veya direk adı.");

        jButton2.setText("Dosya Seç");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jCheckBox1.setText("Parçalanan Dosyayı Sil.");

        jButton3.setText("İşlem Listesini Temizle.");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Durdur");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(2, 2, 2)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int durdur = 0;
  
    javax.swing.DefaultListModel durumlistesi = new javax.swing.DefaultListModel();
    public void shredder(String dosyakonumu, int parcalamasayisi){
    
        try {
         String karakterler = "qwertyuopasdfghjklizxcvbnmQWERTYUOPASDFGHJKLIZXCVBNM>#{[]}-!^+%&/()+-@*?;1234567890";
         java.util.Random anan = new java.util.Random();
         String randomkarakter = "";
         if(jTextField3.getText().equals("")) {
        for (int sa = 0; sa < 100; sa = sa + 1 ) {
       
            randomkarakter += karakterler.charAt(anan.nextInt(karakterler.length() -1));
         }
      
        for (int parcala = 0; parcala < parcalamasayisi; parcala = parcala + 1) {
            java.io.FileWriter yazdirci = new java.io.FileWriter(dosyakonumu);
            yazdirci.write(randomkarakter);
            yazdirci.close();
    
            durumlistesi.addElement(dosyakonumu + " Parçalanıyor : Parçalama Sayısı : " + parcala + ":" + parcalamasayisi);
            jList1.setModel(durumlistesi);
            
            if(jCheckBox1.isSelected()) {
                java.io.File dosyasil = new java.io.File(dosyakonumu);
                dosyasil.delete();
                durumlistesi.addElement(dosyakonumu + " Dosya Silindi.");
                 jList1.setModel(durumlistesi);
            }
         
           }
         }
         else {
                if(dosyakonumu.contains(jTextField3.getText())) {
                 durumlistesi.addElement(dosyakonumu + " Dosya Es Geçildi : " + jTextField3.getText() + " Adlı Uzantı İstisna Edildi.");
                 jList1.setModel(durumlistesi);
            }
           else
           {
         for (int sa = 0; sa < 100; sa = sa + 1 ) {
           randomkarakter += karakterler.charAt(anan.nextInt(karakterler.length() -1));
         }
     
        for (int parcala = 0; parcala < parcalamasayisi; parcala = parcala + 1) {
            java.io.FileWriter yazdirci = new java.io.FileWriter(dosyakonumu);
            yazdirci.write(randomkarakter);
            yazdirci.close();
         
                 durumlistesi.addElement(dosyakonumu + " Parçalanıyor : Parçalama Sayısı : " + parcala + ":" + parcalamasayisi);
                 
                 jList1.setModel(durumlistesi);
               
             if(jCheckBox1.isSelected()) {
                java.io.File dosyasil = new java.io.File(dosyakonumu);
                dosyasil.delete();
                durumlistesi.addElement(dosyakonumu + " Dosya Silindi.");
                 jList1.setModel(durumlistesi);
            }
      
               }
           }
          }
       } catch (Exception e) {
            durdur = 1;
            javax.swing.JOptionPane.showMessageDialog(null, e, "KFS",   javax.swing.JOptionPane.ERROR_MESSAGE);
         }
  
    }
        
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
        jTextField3.setVisible(false);
        jLabel3.setVisible(false);
        jButton2.setText("Dosya Seç");
        jTextField3.setText("");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
        jTextField3.setVisible(true);
        jLabel3.setVisible(true);
        jButton2.setText("Klasör Seç");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected()) {
                if(jTextField1.getText().equals("")) {
                durumlistesi.addElement("Parçalanacak dosyanın konumunu belirtin.");
                jList1.setModel(durumlistesi);
           
      }
      else
      {
      try {
       durumlistesi.addElement("Parçalama Başlatılıyor...");
       jTextField3.setEnabled(false);
       jTextField1.setEnabled(false);
       jTextField2.setEnabled(false);
       jButton3.setEnabled(false);
       jList1.setModel(durumlistesi);
      jButton4.setEnabled(true);
      java.io.File dosya = new java.io.File(jTextField1.getText());
      boolean dosyavarmi = dosya.exists();
      if(dosyavarmi == true) {
    
   
        shredder(jTextField1.getText(), Integer.parseInt(jTextField2.getText()));
      
   
      jButton4.setEnabled(false);
      durumlistesi.addElement("Parçalama Tamamlandı.");
      jList1.setModel(durumlistesi);
      jTextField3.setEnabled(true);
      jTextField1.setEnabled(true);
      jTextField2.setEnabled(true);
      jButton3.setEnabled(true);
      }
      else {
         durumlistesi.addElement("Belirtilen dosya bulunamadı. Konumu Doğru Yazdığından Emin Ol.");
         jList1.setModel(durumlistesi);
     
          
      } 
   
    
        } catch (Exception e) {
             javax.swing.JOptionPane.showMessageDialog(null, e, "KFS",   javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    
      }
    
        }
        else {
                if(jTextField1.getText().equals("")) {
                durumlistesi.addElement("Parçalanacak dosyaların konumunu belirtin.");
             jList1.setModel(durumlistesi);
           
      }
      else
      {
      try {
       durumlistesi.addElement("Parçalama Başlatılıyor...");
       jTextField3.setEnabled(false);
       jTextField1.setEnabled(false);
       jTextField2.setEnabled(false);
       jButton3.setEnabled(false);
       jList1.setModel(durumlistesi);
       jButton4.setEnabled(true);
       java.io.File dosya = new java.io.File(jTextField1.getText());
       if(dosya.isDirectory()) {
       String[] dosyalistesi = dosya.list();
       for(String liste : dosyalistesi) {
       if(durdur == 1) {
              durdur = 0;
              jButton4.setEnabled(false);
              break;
      }
        java.io.File dosyami = new java.io.File(dosya + "/" + liste);
        if(dosyami.isFile()) {
             shredder(dosya + "/" + liste, Integer.parseInt(jTextField2.getText())); 
      
        }
        
      
      }
      jButton4.setEnabled(false);
      durumlistesi.addElement("Parçalama Tamamlandı.");
      jList1.setModel(durumlistesi);
             jTextField3.setEnabled(true);
       jTextField1.setEnabled(true);
       jTextField2.setEnabled(true);
       jButton3.setEnabled(true);
      }
      else {
         durumlistesi.addElement("Belirtilen klasör bulunamadı. Konumu Doğru Yazdığından Emin Ol.");
         jList1.setModel(durumlistesi);
     
          
      } 
   
    
        } catch (Exception e) {
             javax.swing.JOptionPane.showMessageDialog(null, e, "KFS",   javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    
      }
    
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    
           javax.swing.JFileChooser sap = new javax.swing.JFileChooser();
        if(jRadioButton1.isSelected()) {
            sap.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
         }
        else {
            sap.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
        }
        int islem = sap.showOpenDialog(sap);
        if (islem == javax.swing.JFileChooser.APPROVE_OPTION) {
          java.io.File dosya = sap.getSelectedFile();
          jTextField1.setText(dosya.getAbsolutePath());
        } 
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       durumlistesi.removeAllElements();
       jList1.setModel(durumlistesi);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         durumlistesi.addElement("Parçalama Durduruldu.");
         jList1.setModel(durumlistesi);
        durdur = 1;
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
